### ISSUE TITLE
brod consumers strange behaviour

### ISSUE THREAD

**Issue by silviucpp** [kafka4beam/brod#220] opened 2017-07-04 07:40 UTC
Hello,

I have a strange behavior with consumers in brod. 

I have a topic with 6 partitions. Using `https://github.com/G-Corp/kafe` when I start multiple instances of the same group subscriber the messages are spread over those instances. If number of instances > number of partitions then some of them will stay in standby and are not receiving any message. Once I kill a subscriber one of the IDLE subscribers will start processing from that topic.

With brod first subscriber process the messages from all topics and all other are not receiving anything. Even if when I start the second subscriber I got :
```
group coordinator (groupId=consume_events,memberId=nonode@nohost/<0.323.0>-8ea23691-b670-4a26-b834-0b8ad9f8e2a8,generation=8,pid=<0.323.0>):
re-joining group, reason:'RebalanceInProgress'
```
but messages are not distributed. second subscriber start processing all of them. 

Btw I'm starting all subscribers from the same ip. 

Any idea ?

My code looks like:

```
-module(consumer_test).

-include_lib("brod/include/brod.hrl").

-behaviour(brod_group_subscriber).

-export([
    start/0,
    init/2,
    handle_message/4
]).

-record(state, {}).

-define(INFO_MSG(Format, Args),
    lager:info(Format, Args)).

start() ->
    Topics  = mod_queue:topics_events(),

    GroupConfig = [
        {offset_commit_policy, commit_to_kafka_v2},
        {offset_commit_interval_seconds, 5}
    ],

    GroupId = <<"consume_events">>,
    ConsumerConfig = [{begin_offset, earliest}],
    brod:start_link_group_subscriber(kafka_client, GroupId, Topics, GroupConfig, ConsumerConfig, ?MODULE, []).

init(Topic, []) ->
    ?INFO_MSG("~p:init pid: ~p topic: ~p", [?MODULE, self(), Topic]),
    {ok, []}.

handle_message(_Topic, Partition, #kafka_message{offset = Offset, value  = Value}, State) ->
    ?INFO_MSG("~p:handle_message pid: ~p value bytes: ~p offset: ~p partition: ~p", [?MODULE, self(), byte_size(Value), Offset, Partition]),
    {ok, ack, State}.
```

**Comment by silviucpp** [comment] 2017-07-04 08:10
Another problem I see is that last message is never consumed and kafka manager always shows a lag equal with number of partitions having messages inside. 

For example I can see in kafka manager:

partition 1 log size 12600 consumer offset: 12599 
partition 5 log size 6300 consumer offset: 6299

And seems for some reason brod is not able to process last message. even if I restart it it's starting from offset  12600 and 6300 so it's skipping last message.

**Comment by silviucpp** [comment] 2017-07-04 13:30
So after I did more testing seems my first conclusion was wrong. Problem is that for brod takes more time to rebalance than in kafe. But a problem I see is the way re-balance takes place. 

For example on a topic with 6 partitions I start 6 consumers in the same group. Once I have all 6 started I see that on some consumers messages from the same topic are processed. 

I was expecting to not see this. I mean that 6 partitions to be assigned one per consumer and to not have consumers start swiping partitions between them

**Comment by id** [comment] 2017-07-07 18:06
Thanks for the report @silviucpp we'll look into this.

**Comment by id** [comment] 2017-07-19 12:42
@silviucpp can you show code example for your last comment where you "start 6 consumers in the same group"?

**Comment by silviucpp** [comment] 2017-07-19 13:04
I don't have too much time this week but basically I started 6 different erlang processes running the same consumer and looked to see how topics are balanced.

**Comment by silviucpp** [comment] 2017-07-19 13:05
@id I used the code from first comment started in 6 different erlang consoles

**Comment by id** [comment] 2017-07-19 13:15
@silviucpp this is kinda wrong. You basically started 6 groups for the same topic. And if all of them had one name, it's no surprise you observed weird behaviour.

When you start group subscriber, it will be consuming messages from all partitions which belong to this topic.

**Comment by silviucpp** [comment] 2017-07-19 13:31
Yes but with all other kafka clients it's working in a different way. All other are balancing topics between instances of the same group (group name is the same) only brod behaves like this.

**Comment by id** [comment] 2017-07-19 13:38
You are right, sorry. Yes, nodes in the same group should balance topic partitions between them.

However, I wasn't able to reproduce your problem with 12 partitions topic and 3 erlang nodes running group subscriber using the code example above.

Will try 6 partitions and 6 nodes.

**Comment by id** [comment] 2017-07-19 13:48
Ok, I spawned 6 nodes in 6 terminal windows one by one, using code example above. The topic they were consuming from had 6 partitions. As soon as 6th subscriber has started and joined the group, every node got exactly 1 partition. Then I started producing messages in every partition in the loop, and as expected every consumer was receiving message from the assigned single partition.

**Comment by id** [comment] 2017-07-19 13:49
Screenshot of my terminal window:
![screen shot 2017-07-19 at 15 48 56](https://user-images.githubusercontent.com/138221/28370148-d75af264-6c99-11e7-95a8-26c13cf41931.png)

**Comment by id** [comment] 2017-07-19 13:52
Or may be I misunderstood your issue?

>  I see that on some consumers messages from the same topic are processed.

did you mean "messages from the same partition" ?

**Comment by silviucpp** [comment] 2017-07-19 14:38
For me from what I remember after rebalance was done without adding any new client I saw that every x minutes another rebalance takes place and partitions are shuffle between the instances. 

I didn't expected to have rebalance without adding/stopping new instances. Anyway I will test more and maybe come up with some steps to replicate.

But the other problem reported:

Another problem I see is that last message is never consumed and kafka manager always shows a lag equal with number of partitions having messages inside.

For example I can see in kafka manager:

partition 1 log size 12600 consumer offset: 12599
partition 5 log size 6300 consumer offset: 6299

And seems for some reason brod is not able to process last message. even if I restart it it's starting from offset 12600 and 6300 so it's skipping last message.

it's easy to replicate do you have any idea from where is ?

**Comment by id** [comment] 2017-07-19 14:42
Are you sure the problem is with brod and not with kafka manager?

The manager might be showing the high watermark offset which will be assigned to the next incoming message, while at the moment there are no messages at this offset.

Can you try to fetch message from this exact offset using `brod:fetch` api or kafkacat?

**Comment by silviucpp** [comment] 2017-07-19 15:29
Hello,
if it's a problem with kafka manager then it should be the same for all clients. But only brod have this problem. librdkafka and kafe are fine

**Comment by silviucpp** [comment] 2017-07-21 14:10
I think I forgot to mention a very important stuff. I used the following brod version: f16dee061edf43ae24d29f3a43804b6469f42d70 which is not yet merged in master (use-kafka-protocol-1.0). In case you cannot replicate with this branch I'll try to digg more

Silviu

**Comment by zmstone** [comment] 2017-07-24 23:03
hi
did you observe (in logs) a partition being assigned to different group
members in the same generation?
if this is the case, please try latest master, and i'll see if i can
reproduce it in a week or so.

or were some messages from the same partition being processed by two or
more members?
--- this is perhaps the overlapping between two assignments. when messages
are small, the consumer may fetch quite many messages in a default
batch-size message-set, then make the processes less responsive to
revoke/new assignment calls.

btw. we recommend one group member per erlang node. within a node, load can
be distributed to different processes by casting messages to worker
processes.

**Comment by zmstone** [comment] 2017-11-09 20:14
@silviucpp it's been a while, by any chance you can still provide some inputs to my questions ?

**Comment by silviucpp** [comment] 2017-11-09 20:45
@zmstone you can close it. I'm not using brod any longer we switched to another library.

Silviu

**Closed as completed** 2017-11-09 20:50 UTC
