### ISSUE TITLE
Move INFO level logs to DEBUG level

### ISSUE THREAD

**Issue by amacciola** [kafka4beam/brod#416] opened 2020-08-27 18:27 UTC
There is a lot of logs right now when connecting to the Kafka brokers that are all INFO level logs. As i would not always want to see this in a production ENV it would be nice to only be able to see these when debugging. So if you could log these as DEBUG level logs i could alter the level for local and develop ENVs only. 

Just a large sample for example:
10:17:00.406 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.900.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_0.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_0.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.410 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.904.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_1.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_1.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.411 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.908.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_2.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_2.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.411 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.912.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_3.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_3.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.412 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.916.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_4.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_4.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.412 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.920.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_5.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_5.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.413 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.924.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_6.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_6.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.413 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.928.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_7.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_7.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.413 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.932.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_8.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_8.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.414 [info] [supervisor: {:local, :brod_sup}, started: [pid: #PID<0.936.0>, id: :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_9.Client", mfargs: {:brod_client, :start_link, [[{"127.0.0.1", 9092}], :"Elixir.Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692Pipeline.Broadway.Producer_9.Client", [connect_timeout: 15000]]}, restart_type: {:permanent, 10}, shutdown: 5000, child_type: :worker]] 10:17:00.446 [info] Group member (Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692,coor=#PID<0.914.0>,cb=#PID<0.911.0>,generation=1): elected=false 10:17:00.446 [info] Group member (Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692,coor=#PID<0.930.0>,cb=#PID<0.927.0>,generation=1): elected=false 10:17:00.446 [info] Group member (Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692,coor=#PID<0.918.0>,cb=#PID<0.915.0>,generation=1): elected=false 10:17:00.447 [info] Group member (Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692,coor=#PID<0.910.0>,cb=#PID<0.907.0>,generation=1): elected=false 10:17:00.447 [info] Group member (Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692,coor=#PID<0.934.0>,cb=#PID<0.931.0>,generation=2): elected=true 10:17:00.447 [info] Group member (Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692,coor=#PID<0.902.0>,cb=#PID<0.896.0>,generation=1): elected=false 10:17:00.447 [info] Group member (Drilldown-119465517-b31791c8-e888-11ea-9675-3af9d3cfb692,coor=#PID<0.914.0>,cb=#PID<0.911.0>,generation=1):

**Comment by k32** [comment] 2020-08-27 19:23
Hi! I dare to say that this is a duplicate of #407 
Switching to OTP21 `logger` will enable finer filtering of the logs.

**Closed as completed** 2020-08-27 19:24 UTC

**Comment by epinault** [comment] 2022-05-19 23:06
can you explain how to do so? cause using elixir I am unable to filter those at compile time as explain here https://hexdocs.pm/logger/Logger.html#module-application-configuration
