### ISSUE TITLE
Default offset reset policy doesn't work, client hangs

### ISSUE THREAD

**Issue by alesasnouski** [kafka4beam/brod#422] opened 2020-10-06 12:33 UTC
Some messages are expired and removed.

brod_consumer <0.3727.0> consumer is suspended, waiting for subscriber <0.3724.0> to resubscribe with new begin_offset

This is not a cast , but ...
```
cast_to_subscriber(Pid, Msg) ->
  try
    Pid ! {self(), Msg},
    ok
  catch _ : _ ->
    ok
  end.
```
This method sends message to topic_subscriber:
{<0.1085.0>, {kafka_fetch_error, <<"xmppcs_wgt1_muc_message_v1">>,0, offset_out_of_range,[]}}

Topic subscriber handles this message this way:

handle_info(_Info, State) ->
  {noreply, State}.

Client hangs.

BTW it's a bad idea not to add logging into last handle_info, handle_call methods ...

**Comment by k32** [comment] 2020-10-06 13:24
Hello,

1. Could you describe in more detail what setup do you use to reproduce the issue? What behaviors do you use and how...

2. The amount of logging would be immense and for troubleshooting we prefer to use tracing, e.g. via redbug. Nonetheless, there is an issue #407 to switch to OTP21 logger, it will lay ground for more fine tuned logging.

**Comment by alesasnouski** [comment] 2020-10-06 13:41
Child specs are like:
```
    subscriber_conf = %{
      client: client_name,
      group_id: group_id,
      topics: [topic_name],
      cb_module: Consumer.Handler,
      init_data: struct(config, %{message_type: message_type, decoder: decoder}),
      message_type: :message_set,
      consumer_config: [],
      group_config: [{:begin_offset, :earliest}]
    }

    %{
      id: String.to_atom("brod_group_subscriber_#{message_type}_messages"),
      start: {:brod_group_subscriber_v2, :start_link, [subscriber_conf]}
    }
```
Offset stored in __consumer_offsets topic is old enough and point to expired and non-existing messages.

**Comment by k32** [comment] 2020-10-06 13:51
> Offset stored in __consumer_offsets topic is old enough and point to expired and non-existing messages.

In this case brod doesn't attempt to recover by resetting the committed offset. `begin_offset` field is only used when there's no committed offset. It's intentional behavior that results in error message, since it indicates data loss and has to be acted upon. If you need to reset offset you need to do it manually, for example using brod CLI.

**Comment by k32** [comment] 2020-10-13 10:41
Unless there's something more, I suggest closing this one.

**Closed as completed** 2020-10-17 08:47 UTC

**Comment by alesasnouski** [comment] 2020-10-19 06:06
Engineering approach 👍 
For those who experiencing this issue ( probably stagings after downtime ) set 
consumer_config: [{:offset_reset_policy, :reset_to_earliest}]
